name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4

    - name: Set up Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'
        check-latest: true
        chromedriver: true

    - name: Verify Chrome and ChromeDriver installation
      id: verify-installation
      run: |
        echo "Google Chrome version:"
        google-chrome --version
        echo "ChromeDriver version:"
        chromedriver --version
        echo "CHROME_BIN=$(which google-chrome)" >> $GITHUB_ENV
        echo "CHROMEDRIVER_PATH=$(which chromedriver)" >> $GITHUB_ENV

    - name: Run script
      env:
        CHROME_BIN: ${{ env.CHROME_BIN }}
        CHROMEDRIVER_PATH: ${{ env.CHROMEDRIVER_PATH }}
      run: |
        python main.py

    - name: Upload HTML files
      uses: actions/upload-artifact@v2
      with:
        name: knowledge_base
        path: knowledge_base